version: '2'
services:
  web:
    restart: unless-stopped
    container_name: plot-service-test
    image: plot-service-test
    networks:
      - custom
    ports:
      - "6009:6009"
    volumes:
      - /var/log/plot-service/test/app:/app/logs

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.60.09.0/24
          gateway: 172.60.09.1

