version: '2'
services:
  web:
    restart: unless-stopped
    container_name: plot-service-desktop
    image: plot-service-desktop
    ports:
      - "8080:6009"
    volumes:
      - ${PWD}/plot-service/logs:/app/logs