version: '2'
services:
  web:
    restart: unless-stopped
    container_name: plot-service-v1
    image: plot-service-v1
    networks:
      - custom
    ports:
      - "6634:6634"
    volumes:
      - /var/log/plot-service/v1/app:/app/logs
      - /data/monitoring/latest/RData:/app/data

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.66.34.0/24
          gateway: 172.66.34.1

