version: '2'
services:
  web:
    restart: unless-stopped
    container_name: plot-service-v1
    image: plot-service-v1
    networks:
      - custom
    ports:
      - "6001:6001"
    volumes:
      - /var/log/plot-service/v1/app:/app/logs

networks:
  custom:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.60.01.0/24
          gateway: 172.60.01.1

