FROM rocker/tidyverse:3.5.2
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>

# Update installed system libraries
RUN apt-get update

#######################################################################
# For the monitor-custom app
RUN install2.r --error \
    ggthemes \
    futile.logger \
    R6 \
    webutils \
    httpuv \
    mime \
    jsonlite \
    base64enc \
    magrittr

# Update httpuv and dependent packages
RUN R --vanilla -e 'update.packages(repos="https://cran.rstudio.com", oldPkgs="httpuv", ask=FALSE)'

# Install latest development versions of packages
RUN installGithub.r \
    MazamaScience/MazamaCoreUtils@main \
    MazamaScience/beakr@main

#######################################################################
# beakr instance configuration
#
# ProxypPass settings are be defined in: /etc/apache2/sites-available/default-ssl.conf
#
# # 6000-6009 plot-service -----------------------------------------------------
# # 6001 -- v1 operational
# # 6009 -- test (development)
# ProxyPass /plot-service/v1 http://127.0.0.1:6001/plot-service/v1
# ProxyPassReverse /plot-service/v1 http://127.0.0.1:6001/plot-service/v1
# ProxyPass /plot-service/test http://127.0.0.1:6009/plot-service/test
# ProxyPassReverse /plot-service/test http://127.0.0.1:6009/plot-service/test
#
# Test these settings with:    sudo apache2ctl configtest
# Reload these settings with:  sudo service apache2 reload
#
# The block of ports 6000-6009 is reserved for the 'plot-service' service
ENV BEAKR_HOST 0.0.0.0
ENV BEAKR_PORT 6009

EXPOSE 6009

#######################################################################
# app
#
# Setup for docker.mazamascience.com

# Environment variables ---------------

# path and cache (see apache ProxyPass settings)
ENV SERVICE_PATH plot-service/test
ENV CACHE_DIR output
ENV CACHE_SIZE 10

# mounted directories
ENV DATA_DIR /app/data
ENV LOG_DIR /app/logs

# Set up the app ----------------------

WORKDIR /app

# beakr app and all associated files
COPY output /app/output
COPY R /app/R

# Start the beakr app when the image starts up
CMD [ "Rscript", "/app/R/plot-service-app.R" ]

