FROM rocker/tidyverse:3.5.1
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>

#######################################################################
# For the monitor-custom app
RUN install2.r --error \
    jug \
    MazamaWebUtils \
    ggthemes

#######################################################################
# jug instance configuration
#
# ProxyPass settings are defined in:  /etc/apache2/sites-enabled/default-ssl.conf
# 
# On haze, we will adopt following protocol for ProxyPass settings:
#  * all monitoring services will be on ports in the range 6000-6099
#  * each unique service will have a block of ports from 60#0-60#9
#  * port 60#0 is reserved for the "latest" version
#  * port 60#X is reseved for version X of a service
#  * port 60#9 is reserved for a "test" version
#
# The block of ports 6000-6009 is reserved for the 'plot-service' service
ENV JUG_HOST 0.0.0.0
ENV JUG_PORT 6009

EXPOSE 6009

#######################################################################
# app
#
# Setup for docker.mazamascience.com

# Environment variables ---------------

# path and cache (see apache ProxyPass settings)
ENV SERVICE_PATH plot-service/test
ENV CACHE_DIR output
ENV CACHE_SIZE 10

# mounted directories
ENV DATA_DIR /app/data
ENV LOG_DIR /app/logs

# Set up the app ----------------------

WORKDIR /app

# jug app and all associated files
COPY plot-service-app.R /app
COPY output /app/output
COPY R /app/R

# Start the jug app when the image starts up
CMD [ "Rscript", "/app/plot-service-app.R" ]

