FROM rocker/tidyverse:3.5.1
MAINTAINER Jonathan Callahan <jonathan@mazamascience.com>

#######################################################################
# For the monitor-custom app
RUN install2.r --error \
    jug \
#   MazamaCoreUtils \
#   MazamaWebUtils \
    ggthemes

# Install latest development versions of packages
RUN installGithub.r \
    MazamaScience/MazamaCoreUtils \
    MazamaScience/MazamaWebUtils

#######################################################################
# jug instance configuration
#
# On joule, ProxypPass settings are defined in:
#
#   /etc/httpd/conf.d/tools.mazamascience.com.conf
#
# # 6000-6009 plot-service -----------------------------------------------------
# # 6001 -- v1 operational
# # 6009 -- test (development)
# ProxyPass /plot-service/v1 http://127.0.0.1:6001/plot-service/v1
# ProxyPassReverse /plot-service/v1 http://127.0.0.1:6001/plot-service/v1
# ProxyPass /plot-service/test http://127.0.0.1:6009/plot-service/test
# ProxyPassReverse /plot-service/test http://127.0.0.1:6009/plot-service/test
#
# Test these settings with:    <CentOS equivalent of "sudo apache2ctl configtest">
# Reload these settings with:  <CentOS equivalent of "sudo service apache2 reload">
#
# The block of ports 6000-6009 is reserved for the 'plot-service' service
ENV JUG_HOST 0.0.0.0
ENV JUG_PORT 6001

EXPOSE 6001

#######################################################################
# app
#
# Setup for docker.mazamascience.com

# Environment variables ---------------

# path and cache (see apache ProxyPass settings)
ENV SERVICE_PATH plot-service/v1
ENV CACHE_DIR output
ENV CACHE_SIZE 1000

# mounted directories
ENV DATA_DIR /app/data
ENV LOG_DIR /app/logs

# Set up the app ----------------------

WORKDIR /app

# jug app and all associated files
COPY plot-service-app.R /app
COPY output /app/output
COPY R /app/R

# Start the jug app when the image starts up
CMD [ "Rscript", "/app/plot-service-app.R" ]

